// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc_jb8J7BH5IpPPlmm8yiLaJ4u2RHD9Ec',
    appId: '1:857558181937:web:bffaee668c4d5fbf634d10',
    messagingSenderId: '857558181937',
    projectId: 'influencer-map-f16c8',
    authDomain: 'influencer-map-f16c8.firebaseapp.com',
    storageBucket: 'influencer-map-f16c8.appspot.com',
    measurementId: 'G-KB6RF0K0F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdcLvdjKiubDfmN4tYjm8QR6ryEM7Wk1A',
    appId: '1:857558181937:android:1225c493bff830c2634d10',
    messagingSenderId: '857558181937',
    projectId: 'influencer-map-f16c8',
    storageBucket: 'influencer-map-f16c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsIVHl2-cWMxayrJECjvKKuLipE56T9-M',
    appId: '1:857558181937:ios:bd06b4f4dc28b0a2634d10',
    messagingSenderId: '857558181937',
    projectId: 'influencer-map-f16c8',
    storageBucket: 'influencer-map-f16c8.appspot.com',
    iosClientId: '857558181937-7v45lo6iil0q17qhqjfvmachr5ulv6vr.apps.googleusercontent.com',
    iosBundleId: 'com.dandypeople.influencerMap',
  );
}
